export const haikus = [
	'Ink dries on rice paper,\nTones rise, then fall into place—\nMeaning finds its form.',
	'Four tones, one syllable,\nAir bends around hidden pitch—\nSense splits into sound.',
	'Kana like raindrops,\nSoft against the page at dusk—\nMemory takes root.',
	'Radicals combine,\nAncient bones beneath the strokes—\nStories interlock.',
	'Brush tip hesitates,\nOne stroke too long changes fate—\nPatience guides the hand.',
	'Morning flashcards wait,\nSilent grids of black and white—\nRepetition hums.',
	'Particles drift light,\nWa, ga, and no in orbit—\nGrammar holds the sky.',
	'Character by heart,\nNot by letter, but by shape—\nMeaning carved in mind.',
	'Stroke order whispers,\nTop to bottom, left to right—\nDiscipline in ink.',
	'Kanji in moonlight,\nEach square a compacted world—\nCenturies breathe slow.',
	'Pinyin scaffolding,\nTemporary wooden beams—\nSoon removed by skill.',
	'Hanzi walls rise tall,\nBrick by brick of memory—\nReading builds the gate.',
	'Listening at night,\nSubtitles flicker and fade—\nEars learn to endure.',
	'Syllables collide,\nConsonants without release—\nTongue seeks balance point.',
	'Dictionary glow,\nFinger traces hidden parts—\nRadicals reveal.',
	'Accent marks like sparks,\nGuiding breath through narrow paths—\nSound sharpens to truth.',
	'JLPT dreams,\nPages rustle like dry leaves—\nWinter of review.',
	'Tone sandhi shifting,\nRules bend under neighbor words—\nLanguage flows alive.',
	'Notebook margins filled,\nTiny glosses crowd the lines—\nThoughts bridge two systems.',
	'Calligraphy hall,\nSilence thicker than the ink—\nEach stroke a verdict.',
	'Homophones gather,\nSame sound, divergent meaning—\nContext breaks the tie.',
	'Grammar like lattice,\nSeen only when climbing high—\nStructure holds the climb.',
	'Subtitle removed,\nScene stands naked, voices raw—\nComprehension tests.',
	'Pitch accent subtle,\nOne drop changes everything—\nTokyo listens.',
	'Flashcard decks expand,\nSpaced recall against forgetting—\nTime becomes a tool.',
	'Ancient oracle,\nCarved on shell and bone long past—\nNow on glowing screens.',
	'Loanwords drift ashore,\nKatakana carries them—\nForeign yet at home.',
	'Measure words align,\nOne book, one cup, one thin sheet—\nCounting shapes the world.',
	'Sentence-final tone,\nRises like a lifted brow—\nQuestion forms in air.',
	'Sino roots entwine,\nAcross borders of empire—\nShared ink, altered sound.',
	'Mistakes spoken loud,\nFace warms under sudden doubt—\nGrowth begins with risk.',
	'Silent reading flow,\nNo translation intervenes—\nThought shifts its language.',
	'Chengyu compact tight,\nFour words hold a fable’s weight—\nHistory compressed.',
	'Verb at sentence end,\nMeaning waits in patient suspense—\nClarity arrives.',
	'Listening drills loop,\nDialogues repeat like waves—\nEdges smooth with time.',
	'Kanji and hanja,\nShared bones, divergent voices—\nScripts mirror and part.',
	'Furigana small,\nGuiding eyes through dense forest—\nTraining wheels of sound.',
	'Tone pairs practiced slow,\nMa to má to mǎ to mà—\nPitch maps inner space.',
	'Cursive grass script runs,\nWild yet bound by hidden law—\nFreedom within form.',
	'Syntax rearranged,\nSubject lost then found again—\nPerspective resets.',
	'Stroke count matters still,\nBalance held in symmetry—\nForm anchors meaning.',
	'Podcast murmurs low,\nDaily commute becomes class—\nCity turns textbook.',
	'Etymology,\nRadical hints at the past—\nLogic beneath art.',
	'Anki at midnight,\nCards surface from darkened deck—\nMemory resists.',
	'Honorifics bow,\nDistance measured in suffix—\nRespect encoded.',
	'Compound words expand,\nTwo ideas fused as one—\nNew concepts emerge.',
	'Listening without fear,\nUnknown words pass like clouds by—\nMeaning still survives.',
	'Shadowing aloud,\nEcho trails the native pace—\nMouth learns foreign rhythm.',
	'Translation fades out,\nDirect thought takes quiet hold—\nSecond self awakes.',
	'Ink, pixel, and voice,\nAncient script in modern hands—\nLearning never ends.',
];

export function RandomHaiku(): string {
	const index = Math.floor(Math.random() * haikus.length);
	return haikus[index];
}
